source 'https://rubygems.org'
gem 'rails', '4.1.8'
gem 'pg'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'tzinfo-data', platforms: [:mingw, :mswin]
gem 'nokogiri'
gem 'roo', '1.13.2'
gem 'jquery-turbolinks'
gem 'kaminari'
gem 'tilt'
gem 'pg_search'
#gem 'textacular'
#gem 'taps-taps'
#gem 'yaml_db'
gem 'thin'
gem 'faster_require'
